version: "3.8"

services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile.debian
    image: jupyterlab-debian:latest
    container_name: jupyterlab-debian
    ports:
      - "127.0.0.1:8000:8888"
    volumes:
      - ./notebook:/root/work
      - ./jupyter-data:/root/.local/share/jupyter
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - jupyter_network

networks:
  jupyter_network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.23.0.0/28
          gateway: 172.23.0.1
        - subnet: fd02::/120
          gateway: fd02::1
